
server:
  port: 9022

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: socialmedianow63@gmail.com
    password: bkswsjjigiakypnj
  datasource:
    url: jdbc:postgresql://${datachanURL}/mydatabase
    username: ${datachanUsername}
    password: ${datachanPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:

      ddl-auto: none
      
      
      
      
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: socialmedianow123456@gmail.com
spring.mail.password: qsoihrlkymvjovnc
spring.mail.properties.mail.smtp.auth: true #needs to be here for email to work, ignore the warning
spring.mail.properties.mail.smtp.starttls.enable: true #needs to be here for email to work, ignore the warning



      

